import Foundation

public enum CorpusCatalog {
    public static let widgets: [String] = ["ActionButton", "AssetImage", "BackButton", "BlockSelector", "Button", "CharacterPreviewComponent", "CheckBox", "CheckBoxContainer", "CircularProgressBar", "CodeEditor", "CompactTextField", "DropdownBox", "DropdownEntry", "DynamicPane", "DynamicPaneContainer", "FloatSliderNumberField", "Group", "ItemGrid", "ItemPreviewComponent", "ItemSlot", "Label", "LabeledCheckBox", "MenuItem", "MultilineTextField", "NumberField", "Panel", "PlayerPreviewComponent", "ProgressBar", "ReorderableListGrip", "SceneBlur", "Slider", "SliderNumberField", "Sprite", "TabButton", "TabNavigation", "TextButton", "TextField", "ToggleButton"]

    public static let widgetProperties: [String: [String]] = [
        "ActionButton": ["ActionName", "Alignment", "Anchor", "Disabled", "LayoutMode", "Visible"],
        "AssetImage": ["Anchor", "FallbackTexturePath"],
        "BlockSelector": ["Anchor", "Capacity", "Style"],
        "Button": ["Anchor", "Background", "Disabled", "FlexWeight", "LayoutMode", "MaskTexturePath", "NavOrder", "OutlineColor", "OutlineSize", "Padding", "PlayerResultButtonStyle", "Sounds", "Style", "TextTooltipStyle", "TooltipText", "Visible", "Width"],
        "CharacterPreviewComponent": ["Anchor", "Padding"],
        "CheckBox": ["Anchor", "Background", "Padding", "Style", "TooltipText"],
        "CheckBoxContainer": ["Anchor", "Background", "LayoutMode", "OutlineColor", "OutlineSize", "Padding"],
        "CircularProgressBar": ["Anchor", "Color", "MaskTexturePath", "Value"],
        "CodeEditor": ["ContentPadding", "FlexWeight", "Padding", "Style"],
        "CompactTextField": ["Anchor", "CollapseSound", "CollapsedWidth", "Decoration", "ExpandSound", "ExpandedWidth", "Padding", "PlaceholderStyle", "PlaceholderText", "Style"],
        "DropdownBox": ["Anchor", "Background", "FlexWeight", "MaxSelection", "NoItemsText", "PanelTitleText", "ShowLabel", "ShowSearchInput", "Style", "Visible"],
        "DropdownEntry": ["Text", "Value"],
        "DynamicPane": ["Anchor", "Background", "FlexWeight", "LayoutMode", "MinSize", "ResizeAt", "ResizerBackground", "ResizerSize", "ScrollbarStyle"],
        "DynamicPaneContainer": ["Anchor", "FlexWeight", "LayoutMode"],
        "FloatSliderNumberField": ["Anchor", "Max", "Min", "NumberFieldContainerAnchor", "NumberFieldMaxDecimalPlaces", "NumberFieldStyle", "Padding", "SliderStyle", "Step", "Value"],
        "Group": ["ActiveTabButtonStyle", "AdminScrollbarStyle", "Alignment", "Anchor", "AutoScrollDown", "BackButtonStyle", "Background", "CancelButtonStyle", "Caption", "CloseButton", "Color", "CompactDropdownStyle", "ContentPadding", "DecorationOffset", "FlexWeight", "HitTestVisible", "Icon", "IconLabelSeparator", "InactiveTabButtonStyle", "Item", "ItemGridHeight", "ItemGridSpecialSlotHeight", "ItemGridSpecialSlotLeftPos", "ItemGridSpecialSlotWidth", "ItemGridY", "KeepScrollPosition", "Label", "LabelPosition", "LayoutMode", "MarginRight", "MaskTexturePath", "Max", "MaxDecimalPlaces", "Min", "MouseIconPosition", "MouseWheelScrollBehaviour", "Name", "NavExclude", "OutlineColor", "OutlineSize", "Overscroll", "Padding", "PagerButtonStyle", "PrimaryButtonStyle", "Qty", "SaveButtonStyle", "ScrollbarStyle", "Sep", "SliderStep", "StatNameLabel", "StatNameValueLabel", "Step", "Sub", "Text", "TextTooltipStyle", "Title", "TooltipText", "Value", "Visible", "Width"],
        "ItemGrid": ["Anchor", "AreItemsDraggable", "Background", "InfoDisplay", "KeepScrollPosition", "Padding", "RenderEmptySlots", "RenderItemQualityBackground", "ScrollbarStyle", "ShowScrollbar", "SlotsPerRow", "Style"],
        "ItemPreviewComponent": ["Anchor", "ItemScale", "Padding"],
        "ItemSlot": ["Anchor", "HitTestVisible", "ItemId", "Quantity", "ShowDurabilityBar", "ShowQualityBackground", "ShowQuantity", "Visible"],
        "Label": ["Alignment", "Anchor", "Background", "FlexWeight", "LabelStyle", "MaskTexturePath", "OutlineColor", "OutlineSize", "Padding", "Style", "Text", "TextSpans", "TextTooltipStyle", "TooltipTextSpans", "Visible"],
        "LabeledCheckBox": ["Anchor", "Style"],
        "MenuItem": ["Padding", "PopupStyle", "SelectedStyle", "Style", "TextTooltipStyle"],
        "MultilineTextField": ["Anchor", "AutoGrow", "Background", "ContentPadding", "FlexWeight", "MaxLength", "MaxLines", "MaxVisibleLines", "Padding", "PlaceholderStyle", "PlaceholderText", "ScrollbarStyle", "Style"],
        "NumberField": ["Anchor", "Background", "FlexWeight", "Format", "Padding", "PlaceholderStyle", "Style", "Value"],
        "Panel": ["Background", "Visible"],
        "PlayerPreviewComponent": ["Anchor", "Scale"],
        "ProgressBar": ["Alignment", "Anchor", "Background", "Bar", "BarTexturePath", "Direction", "EffectHeight", "EffectOffset", "EffectTexturePath", "EffectWidth", "Value"],
        "ReorderableListGrip": ["Anchor", "HoveredBackground", "HoveredIconColor", "TextTooltipStyle", "TooltipText"],
        "Slider": ["Anchor", "FlexWeight", "Max", "Min", "Step", "Style", "Value"],
        "SliderNumberField": ["Anchor", "FlexWeight", "Max", "Min", "NumberFieldContainerAnchor", "NumberFieldStyle", "Padding", "SliderStyle", "Step", "Value"],
        "Sprite": ["Anchor", "Frame", "FramesPerSecond", "TexturePath"],
        "TabButton": ["FlexWeight", "Icon", "IconSelected", "Id", "Text", "TextTooltipStyle", "TooltipText", "Visible"],
        "TabNavigation": ["AllowUnselection", "Anchor", "Background", "FlexWeight", "Padding", "SelectedTab", "Style", "StyleState", "Visible"],
        "TextButton": ["Anchor", "Background", "Disabled", "FlexWeight", "FontSize", "HorizontalAlignment", "LabelStyle", "OutlineColor", "OutlineSize", "Padding", "Sounds", "SpacingTop", "Style", "Text", "TextTooltipShowDelay", "TextTooltipStyle", "TooltipText", "Visible"],
        "TextField": ["Anchor", "AutoFocus", "Background", "Decoration", "FlexWeight", "IsReadOnly", "MaxLength", "OutlineColor", "OutlineSize", "Padding", "PasswordChar", "PlaceholderStyle", "PlaceholderText", "Style", "Value"],
        "ToggleButton": ["Anchor", "CheckedStyle", "Style", "TextTooltipStyle", "TooltipText"],
    ]

    public static let enumValues: [String: [String]] = [
        "Alignment": ["Center", "End", "Horizontal", "Right", "Start", "TopLeft", "Vertical"],
        "Direction": ["End", "Start"],
        "HorizontalAlignment": ["Center", "End", "Start"],
        "InfoDisplay": ["None"],
        "LayoutMode": ["Bottom", "BottomScrolling", "Center", "CenterMiddle", "Full", "Left", "LeftCenterWrap", "LeftScrolling", "Middle", "MiddleCenter", "Right", "Top", "TopScrolling"],
        "MouseWheelScrollBehaviour": ["HorizontalOnly"],
        "PanelAlign": ["Bottom", "Right"],
        "ResizeAt": ["End", "Start"],
        "Side": ["Right"],
        "VerticalAlignment": ["Center", "End", "Start"],
    ]

    public static let recordFields: [String: [String]] = [
        "Activate": ["MaxPitch", "MinPitch", "SoundPath", "StopExistingPlayback", "Volume"],
        "ActiveStyle": ["Default"],
        "Anchor": ["Bottom", "Full", "Height", "Horizontal", "Left", "MaxWidth", "MinWidth", "Right", "Top", "Vertical", "Width"],
        "ArrowAnchor": ["Bottom", "Height", "Right", "Width"],
        "ArrowBackground": ["Default"],
        "AssetButtonStyle": ["Sounds"],
        "AssetTreeTooltipStyle": ["Background", "LabelStyle", "Padding"],
        "AttributeLabelStyle": ["FontSize", "TextColor"],
        "AutoSort": ["Activate", "MouseHover"],
        "Background": ["Anchor", "Border", "Color", "Default", "HorizontalBorder", "TexturePath", "VerticalBorder"],
        "Bar": ["Color"],
        "BindingLabelStyle": ["FontName", "FontSize", "OutlineColor", "RenderUppercase", "TextColor"],
        "BlockSelectorStyle": ["ItemGridStyle", "SlotDeleteIcon", "SlotDropIcon", "SlotHoverOverlay"],
        "BreadcrumbArrowLabelStyle": ["FontSize", "TextColor"],
        "BreadcrumbButtonStyle": ["Default", "Hovered", "Pressed"],
        "BreadcrumbCurrentLabelStyle": ["FontSize", "RenderBold", "TextColor"],
        "BtnL": ["Alignment", "FontSize", "RenderBold", "TextColor", "VerticalAlignment"],
        "BtnLabel": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "BuffCooldownCompleted": ["SoundPath", "Volume"],
        "BuffEffectElapsed": ["SoundPath", "Volume"],
        "BuffStartSound": ["SoundPath", "Volume"],
        "ButtonDisabledState": ["Background", "LabelStyle"],
        "ButtonLabelStyle": ["Alignment", "FontSize", "HorizontalAlignment", "RenderBold", "RenderUppercase", "VerticalAlignment"],
        "ButtonPadding": ["Bottom", "Left", "Right", "Top"],
        "ButtonStyle": ["Default", "Disabled", "Hovered", "Pressed", "Sounds"],
        "ButtonStyleState": ["Background"],
        "ButtonsDestructive": ["Activate", "MouseHover"],
        "ButtonsLight": ["Activate", "MouseHover"],
        "ButtonsMain": ["Activate", "MouseHover"],
        "ButtonsSmall": ["Activate", "MouseHover"],
        "ChangedSound": ["SoundPath", "Volume"],
        "CheckBoxStyle": ["Checked", "Unchecked"],
        "Checked": ["ChangedSound", "DefaultBackground", "DefaultLabelStyle", "HoveredBackground", "HoveredLabelStyle", "PressedBackground", "PressedLabelStyle", "Text"],
        "CheckedStyle": ["Default", "Hovered", "Pressed", "Sounds"],
        "CinematicTextStyle": ["FontSize", "HorizontalAlignment", "TextColor", "Wrap"],
        "ClearButtonStyle": ["Height", "HoveredTexture", "Offset", "PressedTexture", "Side", "Texture", "Width"],
        "Close": ["SoundPath", "Volume"],
        "CloseButtonLabelStyle": ["Alignment", "RenderBold"],
        "CloseSound": ["SoundPath", "Volume"],
        "CmdInputStyle": ["Background", "LabelStyle", "Padding", "PlaceholderTextStyle"],
        "CollapseSound": ["SoundPath", "Volume"],
        "ColorPickerDropdownBoxStyle": ["ArrowAnchor", "ArrowBackground", "Background", "ColorPickerStyle", "Overlay", "PanelBackground", "PanelOffset", "PanelPadding"],
        "ColorPickerStyle": ["ButtonBackground", "ButtonFill", "OpacitySelectorBackground", "TextFieldDecoration", "TextFieldHeight", "TextFieldPadding"],
        "ConnectionErrorSound": ["SoundPath", "Volume"],
        "ContentPadding": ["Horizontal", "Vertical"],
        "Context": ["SoundPath", "Volume"],
        "CreateEyedropSelect": ["SoundPath", "Volume"],
        "CreateEyedropUnselect": ["SoundPath", "Volume"],
        "CreateMaskAdd": ["SoundPath", "Volume"],
        "CursedIconAnchor": ["Bottom", "Height", "Left", "Width"],
        "CursedTooltipArrow": ["TexturePath"],
        "CursedTooltipBackground": ["Border", "TexturePath"],
        "DayBigStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "DayCountStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "DayNumStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "DaySubStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "DayTagStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "DebuffStartSound": ["SoundPath", "Volume"],
        "Decoration": ["Default", "Focused"],
        "Default": ["Anchor", "Background", "BindingLabelStyle", "ClearButtonStyle", "ContentMaskTexturePath", "Icon", "IconAnchor", "IconOpacity", "LabelMaskTexturePath", "LabelStyle", "Overlay"],
        "DefaultBackground": ["Border", "Color", "TexturePath"],
        "DefaultLabelStyle": ["FontName", "FontSize", "HorizontalAlignment", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "DefaultStyle": ["Hovered", "Pressed"],
        "DefaultTabNavigation": ["Activate", "MouseHover"],
        "DefaultTooltipBackground": ["Border", "TexturePath"],
        "DescStyle": ["FontSize", "HorizontalAlignment", "TextColor", "Wrap"],
        "DeselectLocationSound": ["SoundPath", "Volume"],
        "Disabled": ["Background", "LabelMaskTexturePath", "LabelStyle"],
        "DisabledBackground": ["Color"],
        "DisabledLabelStyle": ["TextColor"],
        "DiscardButtonLabelStyle": ["Alignment", "RenderBold"],
        "DraggedHandle": ["Border", "Color", "TexturePath"],
        "DropdownBoxSearchInputStyle": ["Anchor", "ClearButtonStyle", "Icon", "Padding", "PlaceholderStyle", "PlaceholderText"],
        "DropdownBoxSounds": ["Activate", "Close", "MouseHover"],
        "DropdownBoxStyle": ["ArrowHeight", "ArrowWidth", "DefaultArrowTexturePath", "DefaultBackground", "EntriesInViewport", "EntryHeight", "EntryLabelStyle", "EntrySounds", "EntryTooltipStyle", "FocusOutlineColor", "FocusOutlineSize", "HorizontalEntryPadding", "HorizontalPadding", "HoveredArrowTexturePath", "HoveredBackground", "HoveredEntryBackground", "LabelStyle", "NoItemsLabelStyle", "PanelAlign", "PanelBackground", "PanelOffset", "PanelPadding", "PanelScrollbarStyle", "PanelTitleLabelStyle", "PanelWidth", "PressedArrowTexturePath", "PressedBackground", "PressedEntryBackground", "SearchInputStyle", "SelectedEntryLabelStyle", "Sounds"],
        "DurabilityBarAnchor": ["Bottom", "Height", "Left", "Width"],
        "EnterWorld": ["Activate", "Context", "MouseHover"],
        "EntryLabelStyle": ["FontSize", "RenderUppercase", "VerticalAlignment"],
        "EntrySounds": ["Activate"],
        "ErrorStyle": ["Default", "Hovered", "Pressed"],
        "ExpandSound": ["SoundPath", "Volume"],
        "FileDropdownBoxStyle": ["ArrowHeight", "ArrowWidth", "DefaultArrowTexturePath", "DefaultBackground", "HorizontalPadding", "HoveredArrowTexturePath", "HoveredBackground", "LabelStyle", "PanelAlign", "PanelOffset", "PressedArrowTexturePath", "PressedBackground", "Sounds"],
        "FillBrass": ["Background"],
        "FillDanger": ["Background"],
        "FillHighlight": ["Background"],
        "FillPremium": ["Background"],
        "FillSuccess": ["Background"],
        "FillWarning": ["Background"],
        "FilterTabStyle": ["Anchor", "IconAnchor"],
        "Focused": ["Background", "Icon", "OutlineColor", "OutlineSize"],
        "Format": ["MaxDecimalPlaces", "MaxValue", "MinValue", "Step", "Suffix"],
        "Frame": ["Count", "Height", "PerRow", "Width"],
        "Handle": ["Border", "Color", "TexturePath"],
        "HeaderRowStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "HeaderTextButtonLabelStyle": ["FontName", "LetterSpacing", "RenderBold", "TextColor", "VerticalAlignment"],
        "HotbarUp": ["SoundPath", "Volume"],
        "HoverSound": ["MaxPitch", "MinPitch", "SoundPath", "Volume"],
        "Hovered": ["Anchor", "Background", "BindingLabelStyle", "IconOpacity", "LabelMaskTexturePath", "LabelStyle"],
        "HoveredBackground": ["Border", "Color", "TexturePath"],
        "HoveredBackgroundAnchor": ["Height", "Top", "Width"],
        "HoveredEntryBackground": ["Color"],
        "HoveredHandle": ["Border", "Color", "TexturePath"],
        "HoveredItemBackground": ["TexturePath"],
        "HoveredLabelStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "HoveredTexture": ["Color", "TexturePath"],
        "Icon": ["Color", "Height", "Offset", "Texture", "TexturePath", "Width"],
        "IconAnchor": ["Height", "Left", "Width"],
        "IconsPickSound": ["SoundPath", "Volume"],
        "IndicatorStyle": ["Alignment", "FontSize", "RenderBold", "TextColor", "VerticalAlignment"],
        "InputAnchor": ["Bottom", "Height"],
        "InputFieldStyle": ["TextColor"],
        "InputPadding": ["Horizontal"],
        "InputPlaceholderStyle": ["RenderItalics", "TextColor"],
        "ItemBackground": ["TexturePath"],
        "ItemCardName": ["FontSize", "RenderBold", "TextColor", "VerticalAlignment"],
        "ItemCardSub": ["FontSize", "TextColor", "VerticalAlignment"],
        "ItemGridStyle": ["BrokenSlotBackgroundOverlay", "BrokenSlotIconOverlay", "CursedIconAnchor", "CursedIconPatch", "DefaultItemIcon", "DurabilityBar", "DurabilityBarAnchor", "DurabilityBarBackground", "DurabilityBarColorEnd", "DurabilityBarColorStart", "ItemStackActivateSound", "ItemStackHoveredSound", "QuantityPopupSlotOverlay", "SlotBackground", "SlotIconSize", "SlotSize", "SlotSpacing"],
        "ItemLabelStyle": ["FontSize", "RenderBold", "RenderUppercase", "TextColor"],
        "ItemPadding": ["Horizontal", "Vertical"],
        "ItemStackActivateSound": ["MaxPitch", "MinPitch", "SoundPath", "Volume"],
        "ItemStackHoveredSound": ["SoundPath", "Volume"],
        "JoinServerSound": ["SoundPath", "Volume"],
        "JoinWorldSound": ["SoundPath", "Volume"],
        "LabelDark": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "LabelGhost": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "LabelLight": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "LabelMuted": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "LabelStyle": ["Alignment", "FontName", "FontSize", "HorizontalAlignment", "Hovered", "LetterSpacing", "MinShrinkTextToFitFontSize", "OutlineColor", "RenderBold", "RenderItalics", "RenderUppercase", "ShrinkTextToFit", "TextColor", "VerticalAlignment", "Wrap"],
        "LbHeaderStyle": ["FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor"],
        "LegendStyle": ["FontSize", "HorizontalAlignment", "TextColor", "VerticalAlignment"],
        "Lock": ["Activate"],
        "LogoStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "LootQtyStyle": ["FontSize", "HorizontalAlignment", "TextColor"],
        "MainMenuMusic": ["SoundPath", "Volume"],
        "MaxLabelStyle": ["RenderBold", "TextColor"],
        "MouseHover": ["MaxPitch", "MinPitch", "SoundPath", "Volume"],
        "NameStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "Wrap"],
        "NavigationButtonLabelStyle": ["Alignment", "FontSize", "RenderBold", "RenderUppercase", "Sounds", "TextColor", "VerticalAlignment"],
        "NavigationButtonPadding": ["Left"],
        "NavigationButtonSelectedStyle": ["Default", "Hovered", "Sounds"],
        "NavigationButtonStyle": ["Default", "Hovered", "Sounds"],
        "NoItemsLabelStyle": ["TextColor"],
        "NumberFieldContainerAnchor": ["Height", "Left", "Width"],
        "NumberFieldStyle": ["FontSize", "RenderBold", "TextColor"],
        "OpenCreateMapMarkerSound": ["SoundPath", "Volume"],
        "OpenSound": ["SoundPath", "Volume"],
        "Overlay": ["Default"],
        "Padding": ["Bottom", "Full", "Horizontal", "Left", "Right", "Top", "Vertical"],
        "PanelBackground": ["Border", "TexturePath"],
        "PanelPadding": ["Full"],
        "PanelScrollbarStyle": ["Background", "DraggedHandle", "Handle", "HoveredHandle", "Size", "Spacing"],
        "PatchStyle": ["Border", "Color", "HorizontalBorder", "TexturePath", "VerticalBorder"],
        "PerkRowLabel": ["FontSize", "TextColor", "VerticalAlignment"],
        "PerkRowValue": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "PerkRowValuePremium": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "PlaceMarkerSound": ["SoundPath", "Volume"],
        "PlaceholderStyle": ["FontSize", "RenderBold", "RenderItalics", "RenderUppercase", "TextColor"],
        "PlaceholderTextStyle": ["FontSize", "TextColor"],
        "PlaytimeBigStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "PlaytimeLblStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "PointerBackgroundAnchor": ["Height", "Top", "Width"],
        "PopupMenuLayerStyle": ["Background", "BaseHeight", "HoveredItemBackground", "ItemBackground", "ItemIconSize", "ItemLabelStyle", "ItemPadding", "ItemSounds", "MaxWidth", "Padding", "PressedItemBackground", "RowHeight", "TitleBackground", "TitleStyle"],
        "PopupStyle": ["Background", "ButtonPadding", "ButtonStyle", "Padding", "SelectedButtonStyle", "TooltipStyle"],
        "Pressed": ["Anchor", "Background", "IconOpacity", "LabelMaskTexturePath", "LabelStyle"],
        "PressedBackground": ["Border", "Color", "TexturePath"],
        "PressedEntryBackground": ["Color"],
        "PressedItemBackground": ["TexturePath"],
        "PressedLabelStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "PressedTexture": ["Color", "TexturePath"],
        "QeTitleStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "QeValStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "RailLabelStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "VerticalAlignment"],
        "RarityStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor"],
        "RecipeItemGridStyle": ["SlotBackground"],
        "RowItemStyle": ["FontSize", "HorizontalAlignment", "TextColor", "VerticalAlignment"],
        "RowL": ["FontSize", "TextColor", "VerticalAlignment"],
        "RowQtyFreeStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "RowQtyPremStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "RowQtyTotStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "RowTagStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SaveSettings": ["Activate", "MouseHover"],
        "ScrollbarStyle": ["Background", "DraggedHandle", "Handle", "HoveredHandle", "OnlyVisibleWhenHovered", "Size", "Spacing"],
        "SearchActiveStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "SearchInputStyle": ["Anchor", "Background", "ClearButtonStyle", "Icon", "Padding", "PlaceholderStyle", "PlaceholderText", "Style"],
        "SearchPromptStyle": ["FontSize", "HorizontalAlignment", "TextColor", "VerticalAlignment"],
        "SectionHeader": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SectionHintStyle": ["FontSize", "LetterSpacing", "TextColor", "VerticalAlignment"],
        "SectionLabel": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SectionLabelStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SelectLocationSound": ["SoundPath", "Volume"],
        "SelectedBackgroundAnchor": ["Height", "Top", "Width"],
        "SelectedButtonStyle": ["Default", "Hovered"],
        "SelectedEntryIconBackground": ["TexturePath"],
        "SelectedEntryLabelStyle": ["FontSize", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SelectedLabelStyle": ["Default", "Hovered", "TextColor"],
        "SelectedStyle": ["Default", "Hovered", "Pressed"],
        "SelectedTabStyle": ["Default"],
        "ServerList": ["Activate", "MouseHover"],
        "Shuffle": ["Activate"],
        "SignatureReadySound": ["SoundPath", "Volume"],
        "SkipBtnLabel": ["FontSize", "TextColor", "VerticalAlignment"],
        "SliderActivate": ["SoundPath", "Volume"],
        "SliderRelease": ["SoundPath", "Volume"],
        "SliderStyle": ["Background", "Fill", "Handle", "HandleHeight", "HandleWidth", "Sounds"],
        "Sounds": ["Activate", "Context", "MouseHover"],
        "SpecialItemGridStyle": ["SlotBackground"],
        "StaminaErrorSound": ["SoundPath", "Volume"],
        "StartBtnLabel": ["FontSize", "RenderBold", "TextColor", "VerticalAlignment"],
        "StatLabelStyle": ["FontSize", "TextColor", "VerticalAlignment"],
        "StatValueStyle": ["FontSize", "RenderBold", "TextColor", "VerticalAlignment"],
        "StatusStyle": ["FontSize", "HorizontalAlignment", "TextColor", "VerticalAlignment"],
        "StepSectionLabel": ["FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "Style": ["Alignment", "Background", "Checked", "Default", "DefaultBackground", "Disabled", "EntryHeight", "EntryIconHeight", "EntryIconWidth", "EntrySounds", "Fill", "FontName", "FontSize", "Handle", "HandleHeight", "HandleWidth", "HorizontalAlignment", "HorizontalPadding", "Hovered", "HoveredBackground", "IconHeight", "IconTexturePath", "IconWidth", "ItemGridStyle", "LabelStyle", "LetterSpacing", "MinShrinkTextToFitFontSize", "OutlineColor", "PanelAlign", "PanelOffset", "PanelScrollbarStyle", "PanelWidth", "Pressed", "PressedBackground", "RenderBold", "RenderItalics", "RenderUppercase", "SearchInputStyle", "SelectedEntryIconBackground", "SelectedEntryLabelStyle", "SelectedTabStyle", "ShrinkTextToFit", "SlotBackground", "SlotDropIcon", "SlotIconSize", "SlotSize", "SlotSpacing", "Sounds", "TabSounds", "TabStyle", "TextColor", "Unchecked", "VerticalAlignment", "Wrap", "WrapMaxLines"],
        "StyleSelected": ["Default", "Hovered", "Pressed"],
        "StyleState": ["LabelStyle", "Padding"],
        "SubDescStyle": ["FontSize", "TextColor", "Wrap"],
        "SubTitleRtpStyle": ["FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SubTitleStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "SummaryBigStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "SummaryLblStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TabBtnActiveLabel": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TabBtnInactiveLabel": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TabNavigationStyle": ["SelectedTabStyle", "TabSounds", "TabStyle"],
        "TabRailItemActiveLabel": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TabRailItemInactiveLabel": ["Alignment", "FontSize", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TabSounds": ["Activate"],
        "TabStyle": ["Default", "Hovered", "Pressed"],
        "TabStyleState": ["Anchor", "Background", "IconAnchor", "IconOpacity", "LabelStyle", "Overlay", "Padding", "TooltipStyle"],
        "TeleportSound": ["SoundPath", "Volume"],
        "TextButtonStyle": ["Default", "Disabled", "Hovered", "Pressed", "Sounds"],
        "TextButtonStyleState": ["Background", "LabelStyle"],
        "TextFieldDecoration": ["Default"],
        "TextFieldPadding": ["Left"],
        "TextTooltipStyle": ["Alignment", "Background", "LabelStyle", "MaxWidth", "Padding"],
        "Texture": ["Color", "TexturePath"],
        "TierLabelStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TileRewardStyle": ["FontSize", "HorizontalAlignment", "RenderBold", "TextColor", "VerticalAlignment"],
        "TileTitleStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "Tiles": ["Activate", "MouseHover"],
        "TitleBackground": ["TexturePath"],
        "TitleStyle": ["FontSize", "HorizontalAlignment", "LetterSpacing", "RenderBold", "RenderUppercase", "TextColor", "VerticalAlignment"],
        "TooltipStyle": ["LabelStyle", "MaxWidth", "Padding"],
        "TopBar": ["Activate", "MouseHover"],
        "UIClear": ["SoundPath", "Volume"],
        "UnavailableLabelStyle": ["TextColor"],
        "Unchecked": ["ChangedSound", "DefaultBackground", "DefaultLabelStyle", "DisabledBackground", "HoveredBackground", "HoveredLabelStyle", "PressedBackground", "PressedLabelStyle", "Text"],
        "Unlock": ["Activate"],
        "WarningStyle": ["Default", "Hovered", "Pressed"],
        "WorldCreateTiles": ["SoundPath", "Volume"],
    ]

    public static let constructors: [String] = ["Anchor", "BlockSelectorStyle", "ButtonStyle", "ButtonStyleState", "CheckBoxStyle", "ColorPickerDropdownBoxStyle", "ColorPickerStyle", "DropdownBoxSearchInputStyle", "DropdownBoxSounds", "DropdownBoxStyle", "FileDropdownBoxStyle", "InputFieldStyle", "ItemGridStyle", "LabelStyle", "Padding", "PatchStyle", "PopupMenuLayerStyle", "ScrollbarStyle", "SliderStyle", "TabNavigationStyle", "TabStyleState", "TextButtonStyle", "TextButtonStyleState", "TextTooltipStyle"]

    public static let propertyConstructors: [String: [String]] = [
        "AccentBtnStyle": ["TextButtonStyle"],
        "ActionBtnStyle": ["TextButtonStyle"],
        "ActiveTabButtonStyle": ["TextButtonStyle"],
        "AdminScrollbarStyle": ["ScrollbarStyle"],
        "AdventureTileButtonSelectedStyle": ["ButtonStyle"],
        "AdventureTileButtonStyle": ["ButtonStyle"],
        "Anchor": ["Anchor"],
        "BackButtonStyle": ["ButtonStyle"],
        "Background": ["PatchStyle"],
        "BackgroundOnUse": ["PatchStyle"],
        "BackgroundSignatureNotReady": ["PatchStyle"],
        "BackgroundSignatureReady": ["PatchStyle"],
        "BindingButtonBackground": ["PatchStyle"],
        "BindingButtonBackgroundHovered": ["PatchStyle"],
        "BindingButtonBackgroundPressed": ["PatchStyle"],
        "Body": ["LabelStyle"],
        "BodyBold": ["LabelStyle"],
        "BodySmall": ["LabelStyle"],
        "BodyTypeButtonSelectedStyle": ["ButtonStyle"],
        "BodyTypeButtonStyle": ["ButtonStyle"],
        "BoldLabelStyle": ["LabelStyle"],
        "BrushSettingsTabActivatedStyle": ["ButtonStyle"],
        "BrushSettingsTabStyle": ["ButtonStyle"],
        "Btn": ["ButtonStyle"],
        "BuffBackground": ["PatchStyle"],
        "ButtonAnchor": ["Anchor"],
        "ButtonFocusedStyle": ["TextButtonStyle"],
        "ButtonLabelStyle": ["LabelStyle"],
        "ButtonLabelStyleSelected": ["LabelStyle"],
        "ButtonPadding": ["Padding"],
        "ButtonSelectedStyle": ["ButtonStyle", "TextButtonStyle"],
        "ButtonSpacing": ["Anchor"],
        "ButtonStyle": ["ButtonStyle", "TextButtonStyle"],
        "ButtonTextTooltipStyle": ["TextTooltipStyle"],
        "CancelButtonStyle": ["TextButtonStyle"],
        "CardBtnStyle": ["TextButtonStyle"],
        "CategoryButtonActiveAnchor": ["Anchor"],
        "CategoryButtonAnchor": ["Anchor"],
        "CategoryButtonBackground": ["PatchStyle"],
        "CategoryStyle": ["ButtonStyle"],
        "CharCardBtnStyle": ["ButtonStyle"],
        "CheckBoxStyle": ["CheckBoxStyle"],
        "ClaimBtnStyle": ["TextButtonStyle"],
        "ClearBtnStyle": ["ButtonStyle"],
        "ColorPickerDropdownBoxStyle": ["ColorPickerDropdownBoxStyle"],
        "ColorPickerStyle": ["ColorPickerStyle"],
        "CompactDropdownStyle": ["DropdownBoxStyle"],
        "ContentPadding": ["Padding"],
        "CreativeTileButtonSelectedStyle": ["ButtonStyle"],
        "CreativeTileButtonStyle": ["ButtonStyle"],
        "CustomBtnStyle": ["ButtonStyle"],
        "CustomLabelStyle": ["LabelStyle"],
        "CustomStyle": ["TextButtonStyle"],
        "DangerBtnStyle": ["TextButtonStyle"],
        "DarkBlackOverlayBackground": ["PatchStyle"],
        "DebuffBackground": ["PatchStyle"],
        "Default": ["ButtonStyleState", "TextButtonStyleState"],
        "DefaultBlockSelectorStyle": ["BlockSelectorStyle"],
        "DefaultCheckBoxStyle": ["CheckBoxStyle"],
        "DefaultColorPickerDropdownBoxStyle": ["ColorPickerDropdownBoxStyle"],
        "DefaultColorPickerStyle": ["ColorPickerStyle"],
        "DefaultDropdownBoxEntryLabelStyle": ["LabelStyle"],
        "DefaultDropdownBoxLabelStyle": ["LabelStyle"],
        "DefaultDropdownBoxStyle": ["DropdownBoxStyle"],
        "DefaultExtraSpacingScrollbarStyle": ["ScrollbarStyle"],
        "DefaultFileDropdownBoxStyle": ["FileDropdownBoxStyle"],
        "DefaultInputFieldPlaceholderStyle": ["InputFieldStyle"],
        "DefaultInputFieldStyle": ["InputFieldStyle"],
        "DefaultItemGridStyle": ["ItemGridStyle"],
        "DefaultLabelStyle": ["LabelStyle"],
        "DefaultPlaceholderScrollbarStyle": ["ScrollbarStyle"],
        "DefaultPopupMenuLayerStyle": ["PopupMenuLayerStyle"],
        "DefaultScrollbarStyle": ["ScrollbarStyle"],
        "DefaultSliderStyle": ["SliderStyle"],
        "DestructiveButtonStyle": ["ButtonStyle"],
        "DestructiveTextButtonStyle": ["TextButtonStyle"],
        "DialogueBodyStyle": ["LabelStyle"],
        "DialogueNpcNameStyle": ["LabelStyle"],
        "DialogueRoleStyle": ["LabelStyle"],
        "DisabledBackground": ["PatchStyle"],
        "DropdownBox": ["DropdownBoxSounds"],
        "DropdownBoxStyle": ["DropdownBoxStyle"],
        "EmptyTileBackground": ["PatchStyle"],
        "EntryBtnStyle": ["ButtonStyle"],
        "EntryLabelStyle": ["LabelStyle"],
        "EntryStyle": ["ButtonStyle"],
        "ExplorationTileButtonSelectedStyle": ["ButtonStyle"],
        "ExplorationTileButtonStyle": ["ButtonStyle"],
        "FileButtonAnchor": ["Anchor"],
        "FileButtonPadding": ["Padding"],
        "FileButtonStyle": ["TextButtonStyle"],
        "FileButtonStyleSelected": ["TextButtonStyle"],
        "FileDropdownBoxStyle": ["FileDropdownBoxStyle"],
        "FooterBtnStyle": ["TextButtonStyle"],
        "GuildCardBtnPrimaryStyle": ["ButtonStyle"],
        "GuildCardBtnSecondaryStyle": ["ButtonStyle"],
        "HeaderTabStyle": ["TabStyleState"],
        "HeaderTabsStyle": ["TabNavigationStyle"],
        "HeaderTextButtonStyle": ["TextButtonStyle"],
        "HeadlineLabelStyle": ["LabelStyle"],
        "Hovered": ["ButtonStyleState", "TextButtonStyleState"],
        "IconMouseLeftClick": ["PatchStyle"],
        "IconMouseLeftClickHold": ["PatchStyle"],
        "IconMouseMiddleClick": ["PatchStyle"],
        "IconMouseRightClick": ["PatchStyle"],
        "IconMouseRightClickHold": ["PatchStyle"],
        "IconOnlyTopTabAnchor": ["Anchor"],
        "IconOnlyTopTabStyle": ["TabStyleState"],
        "IconOnlyTopTabsStyle": ["TabNavigationStyle"],
        "InactiveTabButtonStyle": ["TextButtonStyle"],
        "InputBoxBackground": ["PatchStyle"],
        "InputBoxHoveredBackground": ["PatchStyle"],
        "InputBoxPressedBackground": ["PatchStyle"],
        "InputBoxSelectedBackground": ["PatchStyle"],
        "InputSlotIcon": ["PatchStyle"],
        "InventoryClearDefaultStyle": ["ButtonStyle"],
        "InventoryClearWarnStyle": ["ButtonStyle"],
        "ItemCategoryButtonActiveBackground": ["PatchStyle"],
        "ItemCategoryButtonAnchor": ["Anchor"],
        "ItemCategoryButtonBackground": ["PatchStyle"],
        "ItemGridStyle": ["ItemGridStyle"],
        "JobsCardBtnStyle": ["ButtonStyle"],
        "LabelStyle": ["LabelStyle"],
        "LibBtnStyle": ["TextButtonStyle"],
        "LightBlackOverlayBackground": ["PatchStyle"],
        "LockedBtnStyle": ["TextButtonStyle"],
        "MaskSettingsTabActivatedStyle": ["ButtonStyle"],
        "MaskSettingsTabStyle": ["ButtonStyle"],
        "MatchHairColorsOffButtonStyle": ["ButtonStyle"],
        "MatchHairColorsOnButtonStyle": ["ButtonStyle"],
        "MonoLabel": ["LabelStyle"],
        "MonoMuted": ["LabelStyle"],
        "MountCardToggleStyle": ["ButtonStyle"],
        "NavTabStyle": ["ButtonStyle"],
        "NavigationButtonSelectedStyle": ["TextButtonStyle"],
        "NavigationButtonStyle": ["TextButtonStyle"],
        "NavigationItemSelectedStyle": ["LabelStyle"],
        "NavigationItemStyle": ["LabelStyle"],
        "NewsCardBtnStyle": ["ButtonStyle"],
        "OnButtonStyle": ["TextButtonStyle"],
        "OverflowStyle": ["LabelStyle"],
        "OverlayBackground": ["PatchStyle"],
        "Padding": ["Padding"],
        "PageArrowStyle": ["TextButtonStyle"],
        "PagerButtonStyle": ["TextButtonStyle"],
        "PanelBackground": ["PatchStyle"],
        "PanelTaskCompletionComplete": ["LabelStyle"],
        "PanelTaskCompletionInProgress": ["LabelStyle"],
        "PanelTitleLabelStyle": ["LabelStyle"],
        "PartPreviewFrameBackground": ["PatchStyle"],
        "PartPreviewSelectedBackground": ["PatchStyle"],
        "PartPreviewSelectedFrameBackground": ["PatchStyle"],
        "PartPreviewSelectedFrameSize": ["Anchor"],
        "PetCardToggleStyle": ["ButtonStyle"],
        "PlaceholderStyle": ["InputFieldStyle"],
        "PlayerResultButtonStyle": ["ButtonStyle"],
        "PopupMenuLayerStyle": ["PopupMenuLayerStyle"],
        "PopupTitleStyle": ["LabelStyle"],
        "PresetBtnStyle": ["ButtonStyle"],
        "PresetPickBtnStyle": ["ButtonStyle"],
        "Pressed": ["ButtonStyleState", "TextButtonStyleState"],
        "PrimaryButton": ["TextButtonStyle"],
        "PrimaryButtonDefaultBackground": ["PatchStyle"],
        "PrimaryButtonDisabledBackground": ["PatchStyle"],
        "PrimaryButtonDisabledLabelStyle": ["LabelStyle"],
        "PrimaryButtonHoveredBackground": ["PatchStyle"],
        "PrimaryButtonLabelStyle": ["LabelStyle"],
        "PrimaryButtonPressedBackground": ["PatchStyle"],
        "PrimaryButtonStyle": ["ButtonStyle", "TextButtonStyle"],
        "PrimarySquareButtonDefaultBackground": ["PatchStyle"],
        "PrimarySquareButtonDisabledBackground": ["PatchStyle"],
        "PrimarySquareButtonHoveredBackground": ["PatchStyle"],
        "PrimarySquareButtonPressedBackground": ["PatchStyle"],
        "PrimarySquareButtonStyle": ["ButtonStyle"],
        "PrimaryTextButtonStyle": ["TextButtonStyle"],
        "ProgressBarBreach": ["PatchStyle"],
        "ProgressBarGreen": ["PatchStyle"],
        "ProgressBarOrange": ["PatchStyle"],
        "ProgressBarRed": ["PatchStyle"],
        "QeActionStyle": ["TextButtonStyle"],
        "QeAddStyle": ["TextButtonStyle"],
        "QeBtnStyle": ["TextButtonStyle"],
        "QeDelStyle": ["TextButtonStyle"],
        "QeFooterStyle": ["TextButtonStyle"],
        "QeNameStyle": ["TextButtonStyle"],
        "QuestsCardBtnStyle": ["ButtonStyle"],
        "RandomizationLockedButtonStyle": ["ButtonStyle"],
        "RandomizationUnlockedButtonStyle": ["ButtonStyle"],
        "RedoIcon": ["PatchStyle"],
        "RedoIconDisabled": ["PatchStyle"],
        "RightSideButtonActiveStyle": ["ButtonStyle"],
        "RightSideButtonDefaultStyle": ["ButtonStyle"],
        "RowClearBtn": ["ButtonStyle"],
        "RowPresetBtn": ["ButtonStyle"],
        "RowSaveBtn": ["ButtonStyle"],
        "RowStyle": ["TextButtonStyle"],
        "SaveButtonStyle": ["TextButtonStyle"],
        "ScrollbarStyle": ["ScrollbarStyle"],
        "SearchInputStyle": ["DropdownBoxSearchInputStyle"],
        "SecondaryButton": ["TextButtonStyle"],
        "SecondaryButtonDisabledLabelStyle": ["LabelStyle"],
        "SecondaryButtonLabelStyle": ["LabelStyle"],
        "SecondaryButtonStyle": ["ButtonStyle", "TextButtonStyle"],
        "SecondaryTextButtonStyle": ["TextButtonStyle"],
        "SectionTitleStyle": ["LabelStyle"],
        "SelectedEntryLabelStyle": ["LabelStyle"],
        "ServerBrowserButtonDefaultBackground": ["PatchStyle"],
        "ServerBrowserButtonDisabledBackground": ["PatchStyle"],
        "ServerBrowserButtonHoveredBackground": ["PatchStyle"],
        "ServerBrowserButtonPressedBackground": ["PatchStyle"],
        "ServerBrowserRowButtonSelectedStyle": ["ButtonStyle"],
        "ServerBrowserRowButtonStyle": ["ButtonStyle"],
        "ServerBrowserTopTextButtonSelectedStyle": ["TextButtonStyle"],
        "ServerBrowserTopTextButtonStyle": ["TextButtonStyle"],
        "ShortcutBtnStyle": ["ButtonStyle"],
        "ShortcutsConfigBtnStyle": ["ButtonStyle"],
        "SideStatStyle": ["ButtonStyle"],
        "SilencedStyle": ["LabelStyle"],
        "SlotBackground": ["PatchStyle"],
        "SlotBtnStyle": ["TextButtonStyle"],
        "SlotIconUnknownRecipe": ["PatchStyle"],
        "SlotInvalidBackground": ["PatchStyle"],
        "SlotLockedIcon": ["PatchStyle"],
        "SlotMemoryLockedItemIcon": ["PatchStyle"],
        "SlotOverlay": ["TextButtonStyle"],
        "SlotPatch": ["PatchStyle"],
        "SlotPatchActive": ["PatchStyle"],
        "SlotPatchInvalid": ["PatchStyle"],
        "SlotPatchValid": ["PatchStyle"],
        "SlotSelectedBackground": ["PatchStyle"],
        "SlotSelectedOverlay": ["PatchStyle"],
        "SlotTierUpgradeLockedOverlay": ["PatchStyle"],
        "SlotUnlockedIcon": ["PatchStyle"],
        "SlotValidBackground": ["PatchStyle"],
        "SmallBtnStyle": ["TextButtonStyle"],
        "SmallSecondaryButtonDisabledLabelStyle": ["LabelStyle"],
        "SmallSecondaryButtonLabelStyle": ["LabelStyle"],
        "SmallSecondaryTextButtonStyle": ["TextButtonStyle"],
        "StepHeaderNewStyle": ["LabelStyle"],
        "StepHeaderValidateStyle": ["LabelStyle"],
        "StepStatusStyle": ["LabelStyle"],
        "StepTitleStyle": ["LabelStyle"],
        "Style": ["ButtonStyle", "DropdownBoxStyle", "ItemGridStyle", "TextButtonStyle"],
        "SubTitleLabelStyle": ["LabelStyle"],
        "SubtitleStyle": ["LabelStyle"],
        "SuggestionBackground": ["PatchStyle"],
        "SuggestionDescriptionLabelStyle": ["LabelStyle"],
        "SuggestionHintBackground": ["PatchStyle"],
        "SuggestionHintLabelStyle": ["LabelStyle"],
        "SuggestionItemLabelStyle": ["LabelStyle"],
        "SuggestionScrollbarStyle": ["ScrollbarStyle"],
        "SuggestionSectionLabelStyle": ["LabelStyle"],
        "SuggestionSelectionHighlight": ["PatchStyle"],
        "TabAnchor": ["Anchor"],
        "TabArrowAnchor": ["Anchor"],
        "TabBtn": ["TextButtonStyle"],
        "TabBtnStyle": ["TextButtonStyle"],
        "TabButtonSelectedStyle": ["TextButtonStyle"],
        "TabButtonStyle": ["TextButtonStyle"],
        "TabLabelSelectedStyle": ["LabelStyle"],
        "TabLabelStyle": ["LabelStyle"],
        "TagTextButtonLabelStyle": ["LabelStyle"],
        "TagTextButtonStyle": ["TextButtonStyle"],
        "TaskCompletionInProgress": ["LabelStyle"],
        "TaskDescInProgress": ["LabelStyle"],
        "TaskIconComplete": ["PatchStyle"],
        "TaskIconInProgress": ["PatchStyle"],
        "TaskLabelComplete": ["LabelStyle"],
        "TaskLabelStyle": ["LabelStyle"],
        "TertiaryActiveButtonBackground": ["PatchStyle"],
        "TertiaryButtonStyle": ["ButtonStyle"],
        "TertiaryDefaultButtonBackground": ["PatchStyle"],
        "TertiaryDisabledButtonBackground": ["PatchStyle"],
        "TertiaryHoveredButtonBackground": ["PatchStyle"],
        "TertiaryPressedButtonBackground": ["PatchStyle"],
        "TertiaryTextButtonStyle": ["TextButtonStyle"],
        "TextBrass": ["LabelStyle"],
        "TextBrassMid": ["LabelStyle"],
        "TextDanger": ["LabelStyle"],
        "TextMuted": ["LabelStyle"],
        "TextPremium": ["LabelStyle"],
        "TextSuccess": ["LabelStyle"],
        "TextTooltipStyle": ["TextTooltipStyle"],
        "TextTopTabAnchor": ["Anchor"],
        "TextTopTabStyle": ["TabStyleState"],
        "TextTopTabsStyle": ["TabNavigationStyle"],
        "TitleDisplay": ["LabelStyle"],
        "TitleH1": ["LabelStyle"],
        "TitleH2": ["LabelStyle"],
        "TitleH3": ["LabelStyle"],
        "TitleLabelStyle": ["LabelStyle"],
        "TitleStyle": ["LabelStyle"],
        "TitledDropdownBoxStyle": ["DropdownBoxStyle"],
        "ToggleOffStyle": ["ButtonStyle"],
        "ToggleOnStyle": ["ButtonStyle"],
        "TpBtnStyle": ["TextButtonStyle"],
        "TranslucentScrollbarStyle": ["ScrollbarStyle"],
        "TriggerBtnStyle": ["ButtonStyle"],
        "TypeButtonLabelStyle": ["LabelStyle"],
        "TypeButtonStyle": ["TextButtonStyle"],
        "TypeDescriptionStyle": ["LabelStyle"],
        "UndoIcon": ["PatchStyle"],
        "UndoIconDisabled": ["PatchStyle"],
        "VoteBtnStyle": ["ButtonStyle"],
        "VoteCardBtnPrimaryStyle": ["ButtonStyle"],
        "VoteCardBtnSecondaryStyle": ["ButtonStyle"],
    ]

    public static let propertyKind: [String: String] = [
        "AccentBarLeft": "reference",
        "AccentBarLeftPremium": "reference",
        "AccentBtnStyle": "constructor",
        "ActionBtnStyle": "constructor",
        "ActionButtonHeight": "number",
        "ActionButtonIconSize": "number",
        "ActionButtonWidth": "number",
        "ActionName": "binding",
        "Activate": "reference",
        "ActiveStyle": "record",
        "ActiveTabButtonStyle": "constructor",
        "AdditionalIconOffset": "number",
        "AdditionalIconSize": "number",
        "AdminScrollbarStyle": "constructor",
        "AdventureBarFill": "string",
        "AdventureIcon": "string",
        "AdventureIconPath": "string",
        "AdventureIconSelectedPath": "string",
        "AdventureTileButtonSelectedStyle": "constructor",
        "AdventureTileButtonStyle": "constructor",
        "Alignment": "enum",
        "AllowUnselection": "bool",
        "Anchor": "reference",
        "AreItemsDraggable": "bool",
        "ArrowAnchor": "record",
        "ArrowBackground": "record",
        "ArrowHeight": "number",
        "ArrowWidth": "number",
        "AssetButtonStyle": "record",
        "AssetTreeTooltipStyle": "record",
        "AttributeLabelStyle": "record",
        "AutoFocus": "bool",
        "AutoGrow": "bool",
        "AutoScrollDown": "bool",
        "AutoSort": "record",
        "BackButtonStyle": "constructor",
        "Background": "color",
        "BackgroundError": "color",
        "BackgroundInfo": "color",
        "BackgroundOnUse": "constructor",
        "BackgroundSignatureNotReady": "constructor",
        "BackgroundSignatureReady": "constructor",
        "BackgroundSignatureScaleSize": "number",
        "BackgroundSignatureSize": "number",
        "BackgroundSuccess": "color",
        "BackgroundWarning": "color",
        "Bar": "reference",
        "BarHeight": "number",
        "BarLength": "number",
        "BarStructureImagePadding": "number",
        "BarTexturePath": "string",
        "Base": "color",
        "Base05": "color",
        "Base10": "color",
        "Base20": "color",
        "Base25": "color",
        "Base30": "color",
        "Base40": "color",
        "Base50": "color",
        "Base60": "color",
        "Base70": "color",
        "Base75": "color",
        "Base80": "color",
        "Base90": "color",
        "BaseHeight": "number",
        "BigButtonHeight": "number",
        "BindingButtonBackground": "constructor",
        "BindingButtonBackgroundHovered": "constructor",
        "BindingButtonBackgroundPressed": "constructor",
        "BindingLabelStyle": "reference",
        "Body": "reference",
        "BodyBold": "reference",
        "BodySmall": "reference",
        "BodyTypeButtonSelectedStyle": "constructor",
        "BodyTypeButtonStyle": "constructor",
        "BoldLabelStyle": "constructor",
        "Border": "number",
        "Bottom": "number",
        "BottomMargin": "number",
        "BoundKeyColor": "color",
        "BoxSpacing": "number",
        "Brass": "color",
        "Brass05": "color",
        "Brass10": "color",
        "Brass20": "color",
        "Brass25": "color",
        "Brass30": "color",
        "Brass40": "color",
        "Brass50": "color",
        "Brass60": "color",
        "Brass70": "color",
        "Brass75": "color",
        "Brass80": "color",
        "Brass90": "color",
        "BrassDeep": "color",
        "BrassDk": "color",
        "BrassDk05": "color",
        "BrassDk10": "color",
        "BrassDk20": "color",
        "BrassDk25": "color",
        "BrassDk30": "color",
        "BrassDk40": "color",
        "BrassDk50": "color",
        "BrassDk60": "color",
        "BrassDk70": "color",
        "BrassDk75": "color",
        "BrassDk80": "color",
        "BrassDk90": "color",
        "BrassHi": "color",
        "BrassHi05": "color",
        "BrassHi10": "color",
        "BrassHi20": "color",
        "BrassHi25": "color",
        "BrassHi30": "color",
        "BrassHi40": "color",
        "BrassHi50": "color",
        "BrassHi60": "color",
        "BrassHi70": "color",
        "BrassHi75": "color",
        "BrassHi80": "color",
        "BrassHi90": "color",
        "BrassMid": "color",
        "BrassMid05": "color",
        "BrassMid10": "color",
        "BrassMid20": "color",
        "BrassMid25": "color",
        "BrassMid30": "color",
        "BrassMid40": "color",
        "BrassMid50": "color",
        "BrassMid60": "color",
        "BrassMid70": "color",
        "BrassMid75": "color",
        "BrassMid80": "color",
        "BrassMid90": "color",
        "BrassPlaque40": "reference",
        "BrassPlaque56": "reference",
        "BrassPlaquePremium": "reference",
        "BrassSh": "color",
        "BrassSh05": "color",
        "BrassSh10": "color",
        "BrassSh20": "color",
        "BrassSh25": "color",
        "BrassSh30": "color",
        "BrassSh40": "color",
        "BrassSh50": "color",
        "BrassSh60": "color",
        "BrassSh70": "color",
        "BrassSh75": "color",
        "BrassSh80": "color",
        "BrassSh90": "color",
        "BreadcrumbArrowLabelStyle": "record",
        "BreadcrumbButtonStyle": "record",
        "BreadcrumbCurrentLabelStyle": "record",
        "BroadcastOffset": "number",
        "BrokenSlotBackgroundOverlay": "string",
        "BrokenSlotIconOverlay": "string",
        "BrushSettingsTabActivatedStyle": "constructor",
        "BrushSettingsTabStyle": "constructor",
        "Btn": "constructor",
        "BtnL": "record",
        "BtnLabel": "record",
        "BuffBackground": "constructor",
        "BuffCooldownCompleted": "reference",
        "BuffEffectElapsed": "reference",
        "BuffStartSound": "reference",
        "ButtonAnchor": "constructor",
        "ButtonBackground": "string",
        "ButtonBorderSize": "number",
        "ButtonDestructiveSounds": "reference",
        "ButtonDisabledState": "record",
        "ButtonFill": "string",
        "ButtonFocusedStyle": "constructor",
        "ButtonHeight": "number",
        "ButtonLabelStyle": "constructor",
        "ButtonLabelStyleSelected": "constructor",
        "ButtonPadding": "number",
        "ButtonSelectedStyle": "constructor",
        "ButtonSounds": "reference",
        "ButtonSpacing": "number",
        "ButtonStyle": "reference",
        "ButtonText": "binding",
        "ButtonTextTooltipStyle": "constructor",
        "ButtonWidth": "number",
        "ButtonsConnectionError": "string",
        "ButtonsDestructive": "record",
        "ButtonsDestructiveActivate": "string",
        "ButtonsLight": "record",
        "ButtonsLightActivate": "string",
        "ButtonsLightHover": "string",
        "ButtonsMain": "record",
        "ButtonsMainActivate": "string",
        "ButtonsMainHover": "string",
        "ButtonsMainLight": "string",
        "ButtonsSmall": "record",
        "CancelButtonStyle": "constructor",
        "Capacity": "number",
        "Caption": "string",
        "Card": "color",
        "Card05": "color",
        "Card10": "color",
        "Card20": "color",
        "Card25": "color",
        "Card30": "color",
        "Card40": "color",
        "Card50": "color",
        "Card60": "color",
        "Card70": "color",
        "Card75": "color",
        "Card80": "color",
        "Card90": "color",
        "CardBtnStyle": "constructor",
        "CardHeight": "number",
        "CardWidth": "number",
        "CategoryButtonActiveAnchor": "constructor",
        "CategoryButtonAnchor": "constructor",
        "CategoryButtonBackground": "constructor",
        "CategoryStyle": "constructor",
        "CenterPanelWidth": "number",
        "ChangedSound": "record",
        "CharCardBtnStyle": "constructor",
        "CheckBoxStyle": "constructor",
        "Checked": "record",
        "CheckedStyle": "record",
        "ChipBrass": "reference",
        "ChipBrassSurface": "reference",
        "ChipDanger": "reference",
        "ChipDangerSurface": "reference",
        "ChipHighlight": "reference",
        "ChipHighlightSurface": "reference",
        "ChipMythic": "reference",
        "ChipMythicSurface": "reference",
        "ChipSuccess": "reference",
        "ChipSuccessSurface": "reference",
        "ChipWarning": "reference",
        "ChipWarningSurface": "reference",
        "CinematicTextStyle": "record",
        "ClaimBtnStyle": "constructor",
        "ClearBtnStyle": "constructor",
        "ClearButtonStyle": "reference",
        "Close": "record",
        "CloseBtn": "reference",
        "CloseButton": "bool",
        "CloseButtonLabelStyle": "record",
        "CloseSound": "record",
        "CmdInputStyle": "record",
        "CollapseSound": "record",
        "CollapsedWidth": "number",
        "Color": "color",
        "ColorBlueAccent": "color",
        "ColorCaptionLight": "color",
        "ColorDefaultLabel": "color",
        "ColorPickerDropdownBoxStyle": "constructor",
        "ColorPickerStyle": "reference",
        "ColorsPerRow": "number",
        "CompactDropdownStyle": "constructor",
        "ConnectionErrorSound": "record",
        "ContainerBottom": "number",
        "ContainerEmptyBackground": "string",
        "ContainerFullBackground": "string",
        "ContainerMargin": "number",
        "ContainerSize": "number",
        "ContainerSpacing": "number",
        "ContainerWidth": "number",
        "ContentMaskTexturePath": "string",
        "ContentPadding": "number",
        "ContentPaddingFull": "number",
        "ContentSideSpacing": "number",
        "ContentWidth": "number",
        "Context": "record",
        "ContextPaneWidth": "number",
        "CooldownSize": "number",
        "CornerBracketBL": "reference",
        "CornerBracketBR": "reference",
        "CornerBracketTL": "reference",
        "CornerBracketTR": "reference",
        "CornerOrnamentBL": "reference",
        "CornerOrnamentBR": "reference",
        "CornerOrnamentTL": "reference",
        "CornerOrnamentTR": "reference",
        "Count": "number",
        "CreateEyedropSelect": "reference",
        "CreateEyedropUnselect": "reference",
        "CreateMaskAdd": "record",
        "CreativeBarFill": "string",
        "CreativeIcon": "string",
        "CreativeTab": "string",
        "CreativeTileButtonSelectedStyle": "constructor",
        "CreativeTileButtonStyle": "constructor",
        "CursedIconAnchor": "record",
        "CursedIconPatch": "string",
        "CursedTooltipArrow": "record",
        "CursedTooltipBackground": "record",
        "CustomBtnStyle": "constructor",
        "CustomLabelStyle": "constructor",
        "CustomStyle": "constructor",
        "Danger": "color",
        "Danger05": "color",
        "Danger10": "color",
        "Danger20": "color",
        "Danger25": "color",
        "Danger30": "color",
        "Danger40": "color",
        "Danger50": "color",
        "Danger60": "color",
        "Danger70": "color",
        "Danger75": "color",
        "Danger80": "color",
        "Danger90": "color",
        "DangerBtn": "reference",
        "DangerBtnStyle": "constructor",
        "DangerLight": "color",
        "DarkBlackOverlayBackground": "constructor",
        "DarkBlue": "color",
        "DarkGray": "color",
        "DayBigStyle": "record",
        "DayCountStyle": "record",
        "DayNumStyle": "record",
        "DaySubStyle": "record",
        "DayTagStyle": "record",
        "DeadZone": "number",
        "DebuffBackground": "constructor",
        "DebuffStartSound": "reference",
        "Decoration": "record",
        "DecorationHeight": "number",
        "DecorationOffset": "number",
        "DecorationWidth": "number",
        "Default": "string",
        "DefaultArrowTexturePath": "string",
        "DefaultBackground": "color",
        "DefaultBlockSelectorStyle": "constructor",
        "DefaultBtn": "reference",
        "DefaultButtonMinWidth": "number",
        "DefaultCheckBoxStyle": "constructor",
        "DefaultColor": "color",
        "DefaultColorPickerDropdownBoxStyle": "constructor",
        "DefaultColorPickerStyle": "constructor",
        "DefaultDropdownBoxEntryLabelStyle": "constructor",
        "DefaultDropdownBoxLabelStyle": "constructor",
        "DefaultDropdownBoxStyle": "constructor",
        "DefaultExtraSpacingScrollbarStyle": "constructor",
        "DefaultFileDropdownBoxStyle": "constructor",
        "DefaultInputFieldPlaceholderStyle": "constructor",
        "DefaultInputFieldStyle": "constructor",
        "DefaultItemGridBackground": "color",
        "DefaultItemGridPadding": "number",
        "DefaultItemGridStyle": "constructor",
        "DefaultItemIcon": "string",
        "DefaultItemSlotSize": "number",
        "DefaultItemSlotSpacing": "number",
        "DefaultItemSlotsPerRow": "number",
        "DefaultItemSlotsSelector": "number",
        "DefaultLabelColor": "color",
        "DefaultLabelHeight": "number",
        "DefaultLabelStyle": "constructor",
        "DefaultPlaceholderScrollbarStyle": "constructor",
        "DefaultPopupMenuLayerStyle": "constructor",
        "DefaultScrollbarStyle": "constructor",
        "DefaultSliderStyle": "constructor",
        "DefaultStyle": "record",
        "DefaultTabNavigation": "record",
        "DefaultTooltipBackground": "record",
        "DeletedColor": "color",
        "DescStyle": "record",
        "Description": "binding",
        "DeselectLocationSound": "record",
        "DestructiveButtonStyle": "constructor",
        "DestructiveTextButtonStyle": "constructor",
        "DialogueBanner": "reference",
        "DialogueBodyStyle": "reference",
        "DialogueNpcNameStyle": "reference",
        "DialogueRespAdvance": "reference",
        "DialogueRespClose": "reference",
        "DialogueRespDecline": "reference",
        "DialogueRoleStyle": "reference",
        "Direction": "enum",
        "Disabled": "color",
        "DisabledBackground": "constructor",
        "DisabledColor": "color",
        "DisabledLabelStyle": "reference",
        "DiscardButtonLabelStyle": "record",
        "DismissalSound": "record",
        "DraggedHandle": "color",
        "DrainProgressBarAnimationSpeed": "number",
        "DrainProgressTime": "number",
        "DropdownBox": "constructor",
        "DropdownBoxStyle": "reference",
        "DurabilityBar": "string",
        "DurabilityBarAnchor": "record",
        "DurabilityBarBackground": "string",
        "DurabilityBarColorEnd": "color",
        "DurabilityBarColorStart": "color",
        "EditionHeight": "number",
        "EditionSpacing": "number",
        "EditionWidth": "number",
        "EffectHeight": "number",
        "EffectOffset": "number",
        "EffectTexturePath": "string",
        "EffectWidth": "number",
        "EmoteButtonSounds": "reference",
        "EmptyTileBackground": "constructor",
        "EngravedBox": "reference",
        "EngravedBoxSurface": "reference",
        "EnterWorld": "record",
        "EnterWorldActivate": "string",
        "EntriesInViewport": "number",
        "EntryBtnStyle": "constructor",
        "EntryHeight": "number",
        "EntryIconHeight": "number",
        "EntryIconWidth": "number",
        "EntryLabelStyle": "reference",
        "EntrySounds": "reference",
        "EntrySpacing": "number",
        "EntryStyle": "constructor",
        "EntryTooltipStyle": "reference",
        "ErrorAnimationSpeed": "number",
        "ErrorFlashTimer": "number",
        "ErrorIcon": "string",
        "ErrorLabelColor": "color",
        "ErrorStyle": "record",
        "ExpandSound": "record",
        "ExpandedWidth": "number",
        "ExplorationTileButtonSelectedStyle": "constructor",
        "ExplorationTileButtonStyle": "constructor",
        "FallbackTexturePath": "string",
        "FileButtonAnchor": "constructor",
        "FileButtonPadding": "constructor",
        "FileButtonStyle": "constructor",
        "FileButtonStyleSelected": "constructor",
        "FileDropdownBoxStyle": "reference",
        "FileDropdownTemplate": "string",
        "FiligreeDivider": "reference",
        "Fill": "color",
        "FillBrass": "reference",
        "FillDanger": "reference",
        "FillHighlight": "reference",
        "FillPremium": "reference",
        "FillSuccess": "reference",
        "FillWarning": "reference",
        "FilterTab": "string",
        "FilterTabStyle": "record",
        "FlexWeight": "number",
        "FocusOutlineColor": "color",
        "FocusOutlineSize": "number",
        "Focused": "record",
        "FontName": "string",
        "FontSize": "number",
        "FooterBtnStyle": "constructor",
        "Format": "record",
        "Frame": "record",
        "FrameHeight": "number",
        "FrameSpacing": "number",
        "FrameWidth": "number",
        "FramesPerRow": "number",
        "FramesPerSecond": "number",
        "FriendsList": "record",
        "FsBody": "number",
        "FsCaption": "number",
        "FsDisplay": "number",
        "FsH1": "number",
        "FsH2": "number",
        "FsH3": "number",
        "FsMicro": "number",
        "FuelSlotActiveOverlay": "string",
        "FuelSlotIconSize": "number",
        "FuelSlotSize": "number",
        "Full": "number",
        "FullPaddingValue": "number",
        "GameFrame": "reference",
        "GhostBtn": "reference",
        "Gold": "color",
        "Gray": "color",
        "GuildCardBtnPrimaryStyle": "constructor",
        "GuildCardBtnSecondaryStyle": "constructor",
        "HButtonHover": "string",
        "Hairline": "reference",
        "HairlineLight": "reference",
        "Handle": "color",
        "HandleHeight": "number",
        "HandleWidth": "number",
        "HeaderRowStyle": "record",
        "HeaderTabStyle": "constructor",
        "HeaderTabsStyle": "constructor",
        "HeaderTextButtonLabelStyle": "reference",
        "HeaderTextButtonStyle": "constructor",
        "HeadlineLabelStyle": "constructor",
        "Height": "number",
        "Highlight": "color",
        "Highlight05": "color",
        "Highlight10": "color",
        "Highlight20": "color",
        "Highlight25": "color",
        "Highlight30": "color",
        "Highlight40": "color",
        "Highlight50": "color",
        "Highlight60": "color",
        "Highlight70": "color",
        "Highlight75": "color",
        "Highlight80": "color",
        "Highlight90": "color",
        "HitTestVisible": "bool",
        "Horizontal": "number",
        "HorizontalAlignment": "enum",
        "HorizontalBorder": "number",
        "HorizontalEntryPadding": "number",
        "HorizontalPadding": "number",
        "HorizontalPanelSpacing": "number",
        "HotbarDividerControllerOffset": "number",
        "HotbarHeight": "number",
        "HotbarHintSize": "number",
        "HotbarSlotSpacingHud": "number",
        "HotbarSlotSpacingMenu": "number",
        "HotbarUp": "record",
        "HotbarWidthHud": "reference",
        "HotbarWidthMenu": "reference",
        "Hour": "number",
        "HourEntryWidth": "number",
        "HoverSound": "record",
        "Hovered": "reference",
        "HoveredArrowTexturePath": "string",
        "HoveredBackground": "color",
        "HoveredBackgroundAnchor": "record",
        "HoveredEntryBackground": "color",
        "HoveredHandle": "color",
        "HoveredIconColor": "color",
        "HoveredItemBackground": "color",
        "HoveredLabelStyle": "reference",
        "HoveredTexture": "record",
        "Icon": "string",
        "IconAnchor": "record",
        "IconBottomMargin": "number",
        "IconColor": "color",
        "IconHeight": "number",
        "IconMouseLeftClick": "constructor",
        "IconMouseLeftClickHold": "constructor",
        "IconMouseMiddleClick": "constructor",
        "IconMouseRightClick": "constructor",
        "IconMouseRightClickHold": "constructor",
        "IconOnlyTopTabAnchor": "constructor",
        "IconOnlyTopTabStyle": "constructor",
        "IconOnlyTopTabsStyle": "constructor",
        "IconOpacity": "number",
        "IconPatch": "string",
        "IconSelected": "string",
        "IconSelectionColor": "color",
        "IconSelectionMask": "string",
        "IconSize": "number",
        "IconSpacing": "number",
        "IconTexturePath": "string",
        "IconWidth": "number",
        "IconsPickSound": "record",
        "Id": "string",
        "ImageHeight": "number",
        "ImagePath": "string",
        "ImageWidth": "number",
        "InactiveTabButtonStyle": "constructor",
        "IndicatorStyle": "record",
        "InfoDisplay": "enum",
        "InlineStepNewSurface": "reference",
        "InlineStepValidateSurface": "reference",
        "InnerPaddingValue": "number",
        "InputAnchor": "record",
        "InputBackground": "color",
        "InputBoxBackground": "constructor",
        "InputBoxHoveredBackground": "constructor",
        "InputBoxPressedBackground": "constructor",
        "InputBoxSelectedBackground": "constructor",
        "InputHeight": "number",
        "InputPadding": "record",
        "InputPlaceholderStyle": "record",
        "InputSlotActiveOverlay": "string",
        "InputSlotIcon": "constructor",
        "InvalidColor": "color",
        "InventoryClearDefaultStyle": "constructor",
        "InventoryClearWarnStyle": "constructor",
        "InventoryClosedContainerMargin": "reference",
        "InventoryOpenedContainerMargin": "number",
        "IsReadOnly": "bool",
        "Item": "string",
        "ItemBackground": "record",
        "ItemCard": "reference",
        "ItemCardName": "reference",
        "ItemCardSub": "reference",
        "ItemCategoryButtonActiveBackground": "constructor",
        "ItemCategoryButtonAnchor": "constructor",
        "ItemCategoryButtonBackground": "constructor",
        "ItemGridHeight": "number",
        "ItemGridSpecialSlotHeight": "reference",
        "ItemGridSpecialSlotLeftPos": "number",
        "ItemGridSpecialSlotWidth": "reference",
        "ItemGridStyle": "reference",
        "ItemGridY": "number",
        "ItemIconOffset": "number",
        "ItemIconSize": "number",
        "ItemId": "string",
        "ItemLabelStyle": "record",
        "ItemPadding": "record",
        "ItemScale": "number",
        "ItemSlotSize": "reference",
        "ItemSounds": "reference",
        "ItemStackActivateSound": "record",
        "ItemStackHoveredSound": "record",
        "ItemTile": "reference",
        "JobsCardBtnStyle": "constructor",
        "JoinServerSound": "record",
        "JoinWorldSound": "record",
        "KeepScrollPosition": "bool",
        "Label": "string",
        "LabelDark": "record",
        "LabelGhost": "record",
        "LabelLight": "record",
        "LabelMaskTexturePath": "string",
        "LabelMuted": "record",
        "LabelPosition": "number",
        "LabelStyle": "reference",
        "LayoutMode": "enum",
        "LbHeaderStyle": "record",
        "Left": "number",
        "LegendStyle": "record",
        "LetterSpacing": "number",
        "LibBtnStyle": "constructor",
        "LightBlackOverlayBackground": "constructor",
        "LocalHitOpacity": "number",
        "Lock": "record",
        "LockedBtnStyle": "constructor",
        "LogHeight": "number",
        "LogoStyle": "record",
        "LootQtyStyle": "record",
        "LowAlertAnimationSpeed": "number",
        "LowAlertFlashTimer": "number",
        "LowAlertOutlineOpacityStart": "number",
        "MainMenuMusic": "record",
        "MainWidth": "reference",
        "ManaBarHeight": "number",
        "MapMarker": "string",
        "Margin": "number",
        "MarginLeft": "number",
        "MarginRight": "number",
        "MarginTop": "number",
        "MaskSettingsTabActivatedStyle": "constructor",
        "MaskSettingsTabStyle": "constructor",
        "MaskTexturePath": "string",
        "MatchHairColorsOffButtonStyle": "constructor",
        "MatchHairColorsOnButtonStyle": "constructor",
        "Max": "number",
        "MaxDecimalPlaces": "number",
        "MaxLabelStyle": "record",
        "MaxLength": "number",
        "MaxLines": "number",
        "MaxPitch": "number",
        "MaxSelection": "number",
        "MaxValue": "number",
        "MaxVisibleLines": "number",
        "MaxWidth": "number",
        "MessageColorDanger": "color",
        "MessageColorDefault": "color",
        "MessageColorSuccess": "color",
        "MessageColorWarning": "color",
        "MessageSpacing": "number",
        "Metal": "color",
        "Metal05": "color",
        "Metal10": "color",
        "Metal20": "color",
        "Metal25": "color",
        "Metal30": "color",
        "Metal40": "color",
        "Metal50": "color",
        "Metal60": "color",
        "Metal70": "color",
        "Metal75": "color",
        "Metal80": "color",
        "Metal90": "color",
        "MetalHi": "color",
        "MetalHi05": "color",
        "MetalHi10": "color",
        "MetalHi20": "color",
        "MetalHi25": "color",
        "MetalHi30": "color",
        "MetalHi40": "color",
        "MetalHi50": "color",
        "MetalHi60": "color",
        "MetalHi70": "color",
        "MetalHi75": "color",
        "MetalHi80": "color",
        "MetalHi90": "color",
        "Min": "number",
        "MinPitch": "number",
        "MinShrinkTextToFitFontSize": "number",
        "MinSize": "number",
        "MinValue": "number",
        "MinWidth": "number",
        "MinimumDrainValue": "number",
        "MonoLabel": "reference",
        "MonoMuted": "reference",
        "MountCardToggleStyle": "constructor",
        "MouseHover": "reference",
        "MouseIconPosition": "number",
        "MouseWheelScrollBehaviour": "enum",
        "Muted": "color",
        "Muted05": "color",
        "Muted10": "color",
        "Muted20": "color",
        "Muted25": "color",
        "Muted30": "color",
        "Muted40": "color",
        "Muted50": "color",
        "Muted60": "color",
        "Muted70": "color",
        "Muted75": "color",
        "Muted80": "color",
        "Muted90": "color",
        "Mythic": "color",
        "Mythic05": "color",
        "Mythic10": "color",
        "Mythic20": "color",
        "Mythic25": "color",
        "Mythic30": "color",
        "Mythic40": "color",
        "Mythic50": "color",
        "Mythic60": "color",
        "Mythic70": "color",
        "Mythic75": "color",
        "Mythic80": "color",
        "Mythic90": "color",
        "Name": "string",
        "NameColumnWidth": "number",
        "NameHeight": "number",
        "NameIconGap": "number",
        "NameLabelHoverOffset": "number",
        "NameStyle": "record",
        "NavExclude": "bool",
        "NavOrder": "number",
        "NavTabStyle": "constructor",
        "NavigationButtonLabelStyle": "record",
        "NavigationButtonPadding": "record",
        "NavigationButtonSelectedStyle": "constructor",
        "NavigationButtonStyle": "constructor",
        "NavigationItemSelectedStyle": "constructor",
        "NavigationItemStyle": "constructor",
        "NewColor": "color",
        "NewsCardBtnStyle": "constructor",
        "NoItemsLabelStyle": "reference",
        "NoItemsText": "string",
        "NumberFieldContainerAnchor": "record",
        "NumberFieldMaxDecimalPlaces": "number",
        "NumberFieldStyle": "reference",
        "OTypeCraft": "color",
        "OTypeGather": "color",
        "OTypeGo": "color",
        "OTypeKill": "color",
        "OTypeTalk": "color",
        "OffButtonStyle": "reference",
        "Offset": "number",
        "OnButtonStyle": "constructor",
        "OnlineColumnWidth": "number",
        "OnlyVisibleWhenHovered": "bool",
        "OpacitySelectorBackground": "string",
        "OpenCreateMapMarkerSound": "record",
        "OpenSound": "record",
        "OptionsPerRow": "number",
        "OutlineColor": "color",
        "OutlineSize": "number",
        "OverdrawnAlertAnimationSpeed": "number",
        "OverdrawnAlertFlashTimer": "number",
        "OverflowStyle": "constructor",
        "Overlay": "color",
        "OverlayBackground": "constructor",
        "OverlayColor": "color",
        "Overscroll": "bool",
        "Padding": "number",
        "PageArrowStyle": "constructor",
        "PagerButtonStyle": "constructor",
        "PaneSeparatorSize": "number",
        "Panel": "color",
        "Panel05": "color",
        "Panel10": "color",
        "Panel20": "color",
        "Panel25": "color",
        "Panel30": "color",
        "Panel40": "color",
        "Panel50": "color",
        "Panel60": "color",
        "Panel70": "color",
        "Panel75": "color",
        "Panel80": "color",
        "Panel90": "color",
        "PanelAlign": "enum",
        "PanelBackground": "color",
        "PanelOffset": "number",
        "PanelPadding": "number",
        "PanelScrollbarStyle": "reference",
        "PanelSpacing": "reference",
        "PanelTaskCompletionComplete": "constructor",
        "PanelTaskCompletionInProgress": "constructor",
        "PanelTitleHeight": "number",
        "PanelTitleLabelStyle": "constructor",
        "PanelTitleText": "binding",
        "PanelWidth": "number",
        "Parch": "color",
        "Parch05": "color",
        "Parch10": "color",
        "Parch20": "color",
        "Parch25": "color",
        "Parch30": "color",
        "Parch40": "color",
        "Parch50": "color",
        "Parch60": "color",
        "Parch70": "color",
        "Parch75": "color",
        "Parch80": "color",
        "Parch90": "color",
        "PartPreviewBackgroundColor": "color",
        "PartPreviewBackgroundColorHovered": "color",
        "PartPreviewFrameBackground": "constructor",
        "PartPreviewHeight": "number",
        "PartPreviewMargin": "number",
        "PartPreviewRows": "number",
        "PartPreviewSelectedBackground": "constructor",
        "PartPreviewSelectedFrameBackground": "constructor",
        "PartPreviewSelectedFrameSize": "constructor",
        "PartPreviewWidth": "number",
        "PartPreviewsPerRow": "number",
        "PasswordChar": "string",
        "PerRow": "number",
        "PerkRow": "reference",
        "PerkRowLabel": "reference",
        "PerkRowPremium": "reference",
        "PerkRowSurface": "reference",
        "PerkRowValue": "reference",
        "PerkRowValuePremium": "reference",
        "PetCardToggleStyle": "constructor",
        "PingColumnWidth": "number",
        "PlaceMarkerSound": "record",
        "Placeholder": "color",
        "PlaceholderStyle": "reference",
        "PlaceholderText": "string",
        "PlaceholderTextStyle": "record",
        "PlayerResultButtonStyle": "constructor",
        "PlaytimeBigStyle": "record",
        "PlaytimeLblStyle": "record",
        "PointerBackground": "string",
        "PointerBackgroundAnchor": "record",
        "PopupMenuLayerStyle": "constructor",
        "PopupStyle": "record",
        "PopupTitleStyle": "constructor",
        "PortraitBorderInset": "number",
        "PortraitBorderSize": "number",
        "PortraitContentGap": "number",
        "PortraitSize": "number",
        "Premium": "color",
        "Premium05": "color",
        "Premium10": "color",
        "Premium20": "color",
        "Premium25": "color",
        "Premium30": "color",
        "Premium40": "color",
        "Premium50": "color",
        "Premium60": "color",
        "Premium70": "color",
        "Premium75": "color",
        "Premium80": "color",
        "Premium90": "color",
        "PresetBtnStyle": "constructor",
        "PresetPickBtnStyle": "constructor",
        "Pressed": "reference",
        "PressedArrowTexturePath": "string",
        "PressedBackground": "color",
        "PressedEntryBackground": "color",
        "PressedItemBackground": "color",
        "PressedLabelStyle": "reference",
        "PressedTexture": "record",
        "PrimaryBtn": "reference",
        "PrimaryButton": "constructor",
        "PrimaryButtonDefaultBackground": "constructor",
        "PrimaryButtonDisabledBackground": "constructor",
        "PrimaryButtonDisabledLabelStyle": "constructor",
        "PrimaryButtonHeight": "number",
        "PrimaryButtonHoveredBackground": "constructor",
        "PrimaryButtonLabelStyle": "constructor",
        "PrimaryButtonPressedBackground": "constructor",
        "PrimaryButtonStyle": "constructor",
        "PrimaryCursedColor": "color",
        "PrimarySquareButtonDefaultBackground": "constructor",
        "PrimarySquareButtonDisabledBackground": "constructor",
        "PrimarySquareButtonHoveredBackground": "constructor",
        "PrimarySquareButtonPressedBackground": "constructor",
        "PrimarySquareButtonStyle": "constructor",
        "PrimaryTextButtonStyle": "constructor",
        "PrimaryTextColor": "color",
        "ProgressBarAnimationSpeed": "number",
        "ProgressBarBreach": "constructor",
        "ProgressBarErrorThreshold": "number",
        "ProgressBarGreen": "constructor",
        "ProgressBarOrange": "constructor",
        "ProgressBarRed": "constructor",
        "ProgressBarTrack": "reference",
        "QTypeGuilde": "color",
        "QTypeHistoire": "color",
        "QTypeQuotidienne": "color",
        "QTypeSecondaire": "color",
        "QeActionStyle": "constructor",
        "QeAddStyle": "constructor",
        "QeBtnStyle": "constructor",
        "QeDelStyle": "constructor",
        "QeFooterStyle": "constructor",
        "QeNameStyle": "constructor",
        "QeTitleStyle": "record",
        "QeValStyle": "record",
        "Qty": "string",
        "QualityRare": "color",
        "QualityRare05": "color",
        "QualityRare10": "color",
        "QualityRare20": "color",
        "QualityRare25": "color",
        "QualityRare30": "color",
        "QualityRare40": "color",
        "QualityRare50": "color",
        "QualityRare60": "color",
        "QualityRare70": "color",
        "QualityRare75": "color",
        "QualityRare80": "color",
        "QualityRare90": "color",
        "Quantity": "number",
        "QuantityHeight": "number",
        "QuantityPopupSlotOverlay": "string",
        "QuestsCardBtnStyle": "constructor",
        "RailLabelStyle": "record",
        "RandomizationLockedButtonStyle": "constructor",
        "RandomizationUnlockedButtonStyle": "constructor",
        "RarityCommon": "color",
        "RarityEpic": "color",
        "RarityJunk": "color",
        "RarityLegendary": "color",
        "RarityRare": "color",
        "RarityStyle": "record",
        "RarityUncommon": "color",
        "RatingColumnWidth": "number",
        "RecipeItemGridStyle": "reference",
        "RedoIcon": "constructor",
        "RedoIconDisabled": "constructor",
        "RenamedColor": "color",
        "RenderBold": "bool",
        "RenderEmptySlots": "bool",
        "RenderItalics": "bool",
        "RenderItemQualityBackground": "bool",
        "RenderUppercase": "bool",
        "ResizeAt": "enum",
        "ResizerBackground": "color",
        "ResizerSize": "number",
        "RestoreButtonStyle": "reference",
        "Right": "number",
        "RightSideButtonActiveStyle": "constructor",
        "RightSideButtonDefaultStyle": "constructor",
        "RightSideButtonInBetweenSpace": "number",
        "RightSideButtonSize": "number",
        "Rivet10": "reference",
        "Rivet14": "reference",
        "Rivet6": "reference",
        "Rivet8": "reference",
        "RowClearBtn": "constructor",
        "RowHeight": "number",
        "RowItemStyle": "record",
        "RowL": "record",
        "RowPresetBtn": "constructor",
        "RowQtyFreeStyle": "record",
        "RowQtyPremStyle": "record",
        "RowQtyTotStyle": "record",
        "RowSaveBtn": "constructor",
        "RowStyle": "constructor",
        "RowTagStyle": "record",
        "SaveActivate": "string",
        "SaveButtonStyle": "constructor",
        "SaveSettings": "record",
        "Scale": "number",
        "ScrollbarSize": "number",
        "ScrollbarSpace": "number",
        "ScrollbarStyle": "reference",
        "SearchActiveStyle": "record",
        "SearchInputStyle": "constructor",
        "SearchPromptStyle": "record",
        "SecondaryButton": "constructor",
        "SecondaryButtonDisabledLabelStyle": "constructor",
        "SecondaryButtonLabelStyle": "constructor",
        "SecondaryButtonStyle": "constructor",
        "SecondaryMessageColorDanger": "color",
        "SecondaryMessageColorDefault": "color",
        "SecondaryMessageColorSuccess": "color",
        "SecondaryMessageColorWarning": "color",
        "SecondaryTextButtonStyle": "constructor",
        "SectionHeader": "record",
        "SectionHintStyle": "record",
        "SectionLabel": "record",
        "SectionLabelStyle": "record",
        "SectionTitleStyle": "constructor",
        "SelectLocationSound": "record",
        "SelectedBackground": "string",
        "SelectedBackgroundAnchor": "record",
        "SelectedButtonStyle": "record",
        "SelectedEntryIconBackground": "record",
        "SelectedEntryLabelStyle": "reference",
        "SelectedLabelMask": "string",
        "SelectedLabelStyle": "reference",
        "SelectedStyle": "record",
        "SelectedTab": "string",
        "SelectedTabStyle": "record",
        "SelectorPreviewContainerSize": "number",
        "SelectorPreviewSlotIconSize": "number",
        "SelectorPreviewSlotSize": "number",
        "ServerBrowserButtonDefaultBackground": "constructor",
        "ServerBrowserButtonDisabledBackground": "constructor",
        "ServerBrowserButtonHoveredBackground": "constructor",
        "ServerBrowserButtonPressedBackground": "constructor",
        "ServerBrowserRowButtonSelectedStyle": "constructor",
        "ServerBrowserRowButtonStyle": "constructor",
        "ServerBrowserTopTextButtonSelectedStyle": "constructor",
        "ServerBrowserTopTextButtonStyle": "constructor",
        "ServerList": "record",
        "ShadowAndBorderSize": "number",
        "ShortcutBtnStyle": "constructor",
        "ShortcutsConfigBtnStyle": "constructor",
        "ShowDurabilityBar": "bool",
        "ShowIcon": "bool",
        "ShowLabel": "bool",
        "ShowQualityBackground": "bool",
        "ShowQuantity": "bool",
        "ShowScrollbar": "bool",
        "ShowSearchInput": "bool",
        "ShrinkTextToFit": "bool",
        "Shuffle": "record",
        "ShuffleActivate": "string",
        "Side": "enum",
        "SidePanelWidth": "number",
        "SideStatStyle": "constructor",
        "SignatureReadySound": "record",
        "SilencedStyle": "constructor",
        "Size": "number",
        "SkipBtnLabel": "record",
        "SliceAngle": "number",
        "SliderActivate": "record",
        "SliderRelease": "record",
        "SliderStep": "number",
        "SliderStyle": "reference",
        "SlotBackground": "string",
        "SlotBtnStyle": "constructor",
        "SlotDeleteIcon": "string",
        "SlotDropIcon": "string",
        "SlotHoverOverlay": "string",
        "SlotIconSize": "number",
        "SlotIconUnknownRecipe": "constructor",
        "SlotInvalidBackground": "constructor",
        "SlotLockedIcon": "constructor",
        "SlotMemoryLockedItemIcon": "constructor",
        "SlotOverlay": "constructor",
        "SlotPatch": "constructor",
        "SlotPatchActive": "constructor",
        "SlotPatchInvalid": "constructor",
        "SlotPatchValid": "constructor",
        "SlotSelectedBackground": "constructor",
        "SlotSelectedOverlay": "constructor",
        "SlotSize": "number",
        "SlotSpacing": "number",
        "SlotTierUpgradeLockedOverlay": "constructor",
        "SlotUnlockedIcon": "constructor",
        "SlotValidBackground": "constructor",
        "SlotsPerRow": "number",
        "SmallBtnStyle": "constructor",
        "SmallButtonHeight": "number",
        "SmallSecondaryButtonDisabledLabelStyle": "constructor",
        "SmallSecondaryButtonLabelStyle": "constructor",
        "SmallSecondaryTextButtonStyle": "constructor",
        "SoundPath": "string",
        "Sounds": "reference",
        "Sp1": "number",
        "Sp10": "number",
        "Sp12": "number",
        "Sp2": "number",
        "Sp3": "number",
        "Sp4": "number",
        "Sp5": "number",
        "Sp6": "number",
        "Sp7": "number",
        "Sp8": "number",
        "Spacing": "number",
        "SpacingTop": "number",
        "SpecialItemGridStyle": "reference",
        "SpecialSlotBackground": "string",
        "SpecialSlotCompatibleBackground": "string",
        "SpecialSlotHighlightSize": "number",
        "StaminaBarBackground": "string",
        "StaminaBarBackgroundDepleted": "string",
        "StaminaBarBackgroundError": "string",
        "StaminaBarBackgroundErrorOutline": "string",
        "StaminaBarBackgroundOverdrawn": "string",
        "StaminaBarBackgroundOverdrawnOutline": "string",
        "StaminaBarDrainFiller": "string",
        "StaminaBarFiller": "string",
        "StaminaBarFillerCreative": "string",
        "StaminaErrorRenderValue": "number",
        "StaminaErrorSound": "record",
        "StartBtnLabel": "record",
        "StatLabelStyle": "record",
        "StatValueStyle": "record",
        "StatusEffectBarFillGreen": "string",
        "StatusEffectBarFillGrey": "string",
        "StatusEffectBarFillOrange": "string",
        "StatusEffectBarFillRed": "string",
        "StatusEffectBottom": "number",
        "StatusOfflineColor": "color",
        "StatusOnlineColor": "color",
        "StatusSize": "number",
        "StatusSpacing": "number",
        "StatusStyle": "record",
        "Step": "number",
        "StepHeaderNewStyle": "reference",
        "StepHeaderValidateStyle": "reference",
        "StepSectionLabel": "record",
        "StepStatusStyle": "reference",
        "StepTitleStyle": "reference",
        "StopExistingPlayback": "bool",
        "StructureImagePadding": "number",
        "Style": "reference",
        "StyleSelected": "record",
        "StyleState": "record",
        "Sub": "string",
        "SubDescStyle": "record",
        "SubTitleLabelStyle": "constructor",
        "SubTitleRtpStyle": "record",
        "SubTitleStyle": "record",
        "SubtitleStyle": "constructor",
        "Success": "color",
        "Success05": "color",
        "Success10": "color",
        "Success20": "color",
        "Success25": "color",
        "Success30": "color",
        "Success40": "color",
        "Success50": "color",
        "Success60": "color",
        "Success70": "color",
        "Success75": "color",
        "Success80": "color",
        "Success90": "color",
        "SuccessBtn": "reference",
        "SuccessLight": "color",
        "Suffix": "string",
        "SuggestionArgValueColor": "reference",
        "SuggestionBackground": "constructor",
        "SuggestionDescriptionBackground": "reference",
        "SuggestionDescriptionLabelStyle": "constructor",
        "SuggestionDescriptionSpacing": "number",
        "SuggestionDescriptionWidth": "number",
        "SuggestionHintBackground": "constructor",
        "SuggestionHintLabelStyle": "constructor",
        "SuggestionItemHeight": "number",
        "SuggestionItemIndent": "number",
        "SuggestionItemLabelStyle": "constructor",
        "SuggestionLabelHeight": "number",
        "SuggestionMaxVisible": "number",
        "SuggestionMaxWidth": "number",
        "SuggestionMinWidth": "number",
        "SuggestionOptionalArgColor": "reference",
        "SuggestionOuterPadding": "number",
        "SuggestionScrollbarStyle": "constructor",
        "SuggestionSectionLabelColor": "reference",
        "SuggestionSectionLabelStyle": "constructor",
        "SuggestionSelectionHighlight": "constructor",
        "SuggestionTextInset": "number",
        "SuggestionUnhighlightedTextColor": "reference",
        "SuggestionVariantLabelColor": "reference",
        "SummaryBigStyle": "record",
        "SummaryLblStyle": "record",
        "TabAnchor": "constructor",
        "TabArrowAnchor": "constructor",
        "TabArrowTexture": "string",
        "TabBtn": "constructor",
        "TabBtnActive": "reference",
        "TabBtnActiveLabel": "record",
        "TabBtnInactive": "reference",
        "TabBtnInactiveLabel": "record",
        "TabBtnStyle": "constructor",
        "TabButtonSelectedStyle": "constructor",
        "TabButtonStyle": "constructor",
        "TabLabelSelectedStyle": "constructor",
        "TabLabelStyle": "constructor",
        "TabRailItemActive": "reference",
        "TabRailItemActiveLabel": "record",
        "TabRailItemInactive": "reference",
        "TabRailItemInactiveLabel": "record",
        "TabSounds": "reference",
        "TabStyle": "record",
        "TagTextButtonLabelStyle": "constructor",
        "TagTextButtonStyle": "constructor",
        "TagsColumnWidth": "number",
        "TaskCompletionInProgress": "constructor",
        "TaskDescInProgress": "constructor",
        "TaskIconComplete": "constructor",
        "TaskIconInProgress": "constructor",
        "TaskLabelComplete": "constructor",
        "TaskLabelStyle": "constructor",
        "TeleportSound": "record",
        "TertiaryActiveButtonBackground": "constructor",
        "TertiaryButtonStyle": "constructor",
        "TertiaryDefaultButtonBackground": "constructor",
        "TertiaryDisabledButtonBackground": "constructor",
        "TertiaryHoveredButtonBackground": "constructor",
        "TertiaryPressedButtonBackground": "constructor",
        "TertiaryTextButtonStyle": "constructor",
        "Text": "string",
        "Text1": "color",
        "Text2": "color",
        "Text3": "color",
        "TextBrass": "reference",
        "TextBrassMid": "reference",
        "TextColor": "color",
        "TextDanger": "reference",
        "TextFieldDecoration": "record",
        "TextFieldHeight": "number",
        "TextFieldPadding": "record",
        "TextMuted": "reference",
        "TextPremium": "reference",
        "TextSpans": "binding",
        "TextSuccess": "reference",
        "TextTooltipShowDelay": "number",
        "TextTooltipStyle": "reference",
        "TextTopTabAnchor": "constructor",
        "TextTopTabStyle": "constructor",
        "TextTopTabsStyle": "constructor",
        "Texture": "string",
        "TextureBorder": "number",
        "TexturePath": "string",
        "Tick": "string",
        "TierLabelStyle": "record",
        "TileHeight": "number",
        "TileRewardStyle": "record",
        "TileSpacing": "number",
        "TileTitleStyle": "record",
        "TileWidth": "number",
        "Tiles": "record",
        "TilesActivate": "string",
        "TimeStopInfoButtonSize": "number",
        "Title": "string",
        "TitleBackground": "record",
        "TitleBanner": "reference",
        "TitleBannerSurface": "reference",
        "TitleDisplay": "reference",
        "TitleH1": "reference",
        "TitleH2": "reference",
        "TitleH3": "reference",
        "TitleHeight": "number",
        "TitleLabelStyle": "constructor",
        "TitleOffset": "number",
        "TitleStyle": "constructor",
        "TitledDropdownBoxStyle": "constructor",
        "ToggleOffStyle": "constructor",
        "ToggleOnStyle": "constructor",
        "TooltipStyle": "reference",
        "TooltipText": "string",
        "TooltipTextSpans": "binding",
        "Top": "number",
        "TopBar": "record",
        "TopBarActivate": "string",
        "TotalPageContentWidth": "number",
        "TotalWidth": "number",
        "TpBtnStyle": "constructor",
        "TranslucentScrollbarStyle": "constructor",
        "TriggerBtnStyle": "constructor",
        "TypeButtonLabelStyle": "constructor",
        "TypeButtonStyle": "constructor",
        "TypeDescriptionStyle": "constructor",
        "UIClear": "string",
        "UnavailableLabelStyle": "reference",
        "UnboundKeyColor": "color",
        "Unchecked": "record",
        "UndoIcon": "constructor",
        "UndoIconDisabled": "constructor",
        "Unlock": "record",
        "Untick": "string",
        "UtilitySlotContainerControllerOffset": "number",
        "ValidColor": "color",
        "Value": "bool",
        "ValueWidth": "number",
        "Vertical": "number",
        "VerticalAlignment": "enum",
        "VerticalBorder": "number",
        "VerticalPanelSpacing": "number",
        "Visible": "bool",
        "VisibleEntries": "number",
        "VisibleNotifications": "number",
        "Volume": "number",
        "VoteBtnStyle": "constructor",
        "VoteCardBtnPrimaryStyle": "constructor",
        "VoteCardBtnSecondaryStyle": "constructor",
        "Warning": "color",
        "Warning05": "color",
        "Warning10": "color",
        "Warning20": "color",
        "Warning25": "color",
        "Warning30": "color",
        "Warning40": "color",
        "Warning50": "color",
        "Warning60": "color",
        "Warning70": "color",
        "Warning75": "color",
        "Warning80": "color",
        "Warning90": "color",
        "WarningIcon": "string",
        "WarningLabelColor": "color",
        "WarningLight": "color",
        "WarningStyle": "record",
        "Width": "number",
        "WorldCreateTiles": "record",
        "WorldsPerRow": "number",
        "Wrap": "bool",
        "WrapMaxLines": "number",
    ]
}